"""initial schema

Revision ID: 59cb11f2798b
Revises: 
Create Date: 2025-12-24 16:17:04.552061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cb11f2798b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_templates_id'), 'expense_templates', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_annual_payment', sa.Boolean(), nullable=False),
    sa.Column('annual_month', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('income_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_templates_id'), 'income_templates', ['id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    op.create_table('longterm_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starting_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('starting_saving_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('financing_start_month', sa.Date(), nullable=True),
    sa.Column('car_purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('car_down_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('car_final_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('car_monthly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('car_term_months', sa.Integer(), nullable=False),
    sa.Column('car_insurance_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('car_fuel_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('car_maintenance_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('car_tax_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('car_interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('savings_return_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_longterm_plans_id'), 'longterm_plans', ['id'], unique=False)
    op.create_table('saving_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saving_templates_id'), 'saving_templates', ['id'], unique=False)
    op.create_table('savings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_id'), 'savings', ['id'], unique=False)
    op.create_table('longterm_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Date(), nullable=False),
    sa.Column('end_month', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['longterm_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_longterm_periods_id'), 'longterm_periods', ['id'], unique=False)
    op.create_table('template_expense_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['expense_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'expense_id', name='uq_template_expense')
    )
    op.create_index(op.f('ix_template_expense_links_id'), 'template_expense_links', ['id'], unique=False)
    op.create_table('template_income_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['income_id'], ['incomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['income_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'income_id', name='uq_template_income')
    )
    op.create_index(op.f('ix_template_income_links_id'), 'template_income_links', ['id'], unique=False)
    op.create_table('template_saving_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('saving_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['saving_id'], ['savings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['saving_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'saving_id', name='uq_template_saving')
    )
    op.create_index(op.f('ix_template_saving_links_id'), 'template_saving_links', ['id'], unique=False)
    op.create_table('longterm_period_expense_template_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['longterm_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['expense_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'template_id', name='uq_longterm_period_expense_template')
    )
    op.create_index(op.f('ix_longterm_period_expense_template_links_id'), 'longterm_period_expense_template_links', ['id'], unique=False)
    op.create_table('longterm_period_income_template_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['longterm_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['income_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'template_id', name='uq_longterm_period_income_template')
    )
    op.create_index(op.f('ix_longterm_period_income_template_links_id'), 'longterm_period_income_template_links', ['id'], unique=False)
    op.create_table('longterm_period_saving_template_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['longterm_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['saving_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'template_id', name='uq_longterm_period_saving_template')
    )
    op.create_index(op.f('ix_longterm_period_saving_template_links_id'), 'longterm_period_saving_template_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_longterm_period_saving_template_links_id'), table_name='longterm_period_saving_template_links')
    op.drop_table('longterm_period_saving_template_links')
    op.drop_index(op.f('ix_longterm_period_income_template_links_id'), table_name='longterm_period_income_template_links')
    op.drop_table('longterm_period_income_template_links')
    op.drop_index(op.f('ix_longterm_period_expense_template_links_id'), table_name='longterm_period_expense_template_links')
    op.drop_table('longterm_period_expense_template_links')
    op.drop_index(op.f('ix_template_saving_links_id'), table_name='template_saving_links')
    op.drop_table('template_saving_links')
    op.drop_index(op.f('ix_template_income_links_id'), table_name='template_income_links')
    op.drop_table('template_income_links')
    op.drop_index(op.f('ix_template_expense_links_id'), table_name='template_expense_links')
    op.drop_table('template_expense_links')
    op.drop_index(op.f('ix_longterm_periods_id'), table_name='longterm_periods')
    op.drop_table('longterm_periods')
    op.drop_index(op.f('ix_savings_id'), table_name='savings')
    op.drop_table('savings')
    op.drop_index(op.f('ix_saving_templates_id'), table_name='saving_templates')
    op.drop_table('saving_templates')
    op.drop_index(op.f('ix_longterm_plans_id'), table_name='longterm_plans')
    op.drop_table('longterm_plans')
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_income_templates_id'), table_name='income_templates')
    op.drop_table('income_templates')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_expense_templates_id'), table_name='expense_templates')
    op.drop_table('expense_templates')
    # ### end Alembic commands ###